### ISSUE TITLE
 rm redundant code

### ISSUE THREAD

**Issue by PanJiaChen** [halfrost/vue-objccn#1]
https://github.com/halfrost/vue-objccn/blob/master/src/main.js#L9

**Comment by halfrost** [comment]
这里的第9行其实用到了uiv里面的navigationBar，因为开始开发的时候是用BootStrap 3的。大神这么一说，我觉得可以考虑去掉它，换成咱们的 element-ui 里面的navigationBar。

**Comment by PanJiaChen** [comment]
顺便跑一下lint。。。好多冗余代码。。。和格式不对齐

**Comment by halfrost** [comment]
额。。。我新建项目的时候用了eslint了。。是不是我姿势不对？？有些地方格式确实有点奇怪，但是我多缩进几格就报错了。我用的就是 standard 的模式

**Comment by PanJiaChen** [comment]
太松了。。。这lint等于没配。。。

**Comment by halfrost** [comment]
哦，好吧，那我参考一下大神的vue-element-admin里面的eslint可以吧？我看大神这里配置了好多好多。

**Comment by PanJiaChen** [comment]
我觉得你可以拿你司element-ui的配置就可以了。。。我那个是纯自己配置习惯而已

**Comment by halfrost** [comment]
哦哦，行，那我改改，谢谢大神的指点！

**Comment by halfrost** [comment]
呼呼，我用 elemefe 的 eslint 改了一版，大神请过目！

**Comment by PanJiaChen** [comment]
单独跑一下 `npm run lint`  还有很多格式问题。。。
顺便说一句 展示用资源ignore一下咯  有94mb,下了我半天。。。:dizzy_face:

**Comment by halfrost** [comment]
大佬再看看，我现在都 lint 规范好了

**Comment by PanJiaChen** [comment]
:thumbsup:
有空再仔细拜读一下代码
