### ISSUE TITLE
win环境下更改main.js后打包cordova失败

### ISSUE THREAD

**Issue by Liubasara** [halfrost/vue-objccn#12]
ERROR in ./src/main.js

  ✘  http://eslint.org/docs/rules/  Parsing error: Unexpected token

  44 | cordova.initialize()
  45 | // 打开此行代码的注释可以打 cordova 的包
> 46 |
     | ^
  G:\VueDemo\vue-objccn-master\src\main.js:46:1

   ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/null

ERROR in ./src/main.js
Module build failed: SyntaxError: G:/VueDemo/vue-objccn-master/src/main.js: Unex
pected token (46:0)

  44 | cordova.initialize()
  45 | // 打开此行代码的注释可以打 cordova 的包
> 46 |
     | ^

打包成apk后在模拟器和手机上显示都是黑屏...

**Comment by halfrost** [comment]
能说一下你的环境么？比如 npm 的版本，Electron 的版本，cordova 的版本。上面你要更改一下我注释里面说的地方，打开注释再打包。

**Comment by Liubasara** [comment]
找到错误了，main.js文件改掉注释后没有加分号...加上分号后再build一次就不报错了
但好像css文件加载不出来，在模拟器上是这样的
![qq 20171113202845](https://user-images.githubusercontent.com/24971070/32725872-c4d5a520-c8b1-11e7-9c6c-814260568c1c.png)



我的环境
node  v8.9.0
npm  5.5.1
cordova  7.1.0
electron  v1.7.9
webpack 3.8.1

感谢您的及时答复！

**Comment by halfrost** [comment]
嗯嗯。。CSS有点问题。你调试一下，CSS应该报错了。能贴一下错误不？我看能不能帮你解决掉。

**Comment by Liubasara** [comment]
![1](https://user-images.githubusercontent.com/24971070/32768498-fe3a614c-c952-11e7-855a-540d509a8b9f.png)
![2](https://user-images.githubusercontent.com/24971070/32768499-fe744560-c952-11e7-87f2-f9826af81725.png)
打包的时候没有问题，static里也有对应的css文件，但就是访问不了，请问这与hash模式和history模式有关吗？

**Comment by halfrost** [comment]
你看你错误的输出，是在找 file:// 下的 static ，正常的应该是去找 http:// 下的吧。看上面错误，路径好像是相对路径了。如果是绝对路径就没问题。
