### ISSUE TITLE
cordova run ios异常

### ISSUE THREAD

**Issue by lemonwong** [halfrost/vue-objccn#13]
请问，我把vue build之后的代码放在www文件夹下 然后cordova run ios 不能正常预览，是白屏。cordova run browser正常，是ios需要其他的什么配置吗？烦请指点

**Comment by halfrost** [comment]
不用其他的配置，我在代码写了配置，你要打开注释就好了。白屏的话可能是 CSS 出错了。你能贴一下你的错误么？

**Comment by lemonwong** [comment]
我是一个自己的项目 我把做好的vue打包后把生成的文件放在了www文件夹下，请问是不是还需要其他的配置？

**Comment by lemonwong** [comment]
看到了 我先试下

**Comment by lemonwong** [comment]
弄好了，非常感谢
