### ISSUE TITLE
cordova打包时vue-router history模式空白

### ISSUE THREAD

**Issue by lemonwong** [halfrost/vue-objccn#14]
请问下，路由用history模式在用cordova打包成app的时候正常吗，我这里只要路由用history模式，打包出来的app就一片空白，config的assetsPublicPath设置的跟你的是一样的

**Comment by halfrost** [comment]
能告诉我一下你具体在哪里把路由给成 history 模式的么？

**Comment by lemonwong** [comment]
`const router = new Router({
  // mode: "history",
  routes,
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      setTimeout(() => {
        window.scrollTo(savedPosition.x, savedPosition.y);
      }, 200);
    } else {
      return { x: 0, y: 0 };
    }
  }
});

export default router;`

就是在这里了

**Comment by lemonwong** [comment]
const router = new Router({
  // mode: "history",
  routes,
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      setTimeout(() => {
        window.scrollTo(savedPosition.x, savedPosition.y);
      }, 200);
    } else {
      return { x: 0, y: 0 };
    }
  }
});

export default router;

就是在这里了

**Comment by halfrost** [comment]
试了一下。。。好像确实不行。。。我当时好像没有注意到这里。近期一直在忙 Go 的项目。你对这个功能很急么？（不是我吐槽，cordova 的性能放在现在来看真心差。。两年前还勉强可以）

**Comment by lemonwong** [comment]
倒不急，现在用hash能用，就是页面后退的时候记不住上次的浏览位置了，难道跟协议有关？cordova打包的应用，访问页面的时候应该使用的是file://吧 （btw,用cordova也是无奈的过渡之举···）

**Comment by LanhuApp** [comment]
history 模式 需要后端配置,找不到文件时候返回Index从而让前端路由处理，cordova打包放到本地后并没有处理路由问题，所以不行。

**Comment by smileG** [comment]
在服务器上，history 模式需要后端配合 ,找不到文件时返回Index让前端路由处理，在手机APP上，找不到没有处理所以不行。
