### ISSUE TITLE
想问大佬一个问题

### ISSUE THREAD

**Issue by vivinbear** [halfrost/vue-objccn#19]
我怎么调试electron呢?目前看到的命令里没有electron的dev模式呢

**Comment by halfrost** [comment]
electron 的调试，启动的时候默认会打开它的内置浏览器，我每次都是用那个内置浏览器调试的。

**Comment by vivinbear** [comment]
可能是我没有说清楚 就是我的意思是 并没有一个npm 命令 可以让我启动一个开发状态的exe 从而调试主进程渲染进程之类的 我没找到这个

**Comment by halfrost** [comment]
哦。。。好吧。。那这个我没有配过。。运行起来没啥问题就没有怎么调了。。🤪 electron 我研究还不够深。
