### ISSUE TITLE
getIssuesListInfo报错

### ISSUE THREAD

**Issue by fuerpeng** [halfrost/vue-objccn#22]
![qq 20180711202501](https://user-images.githubusercontent.com/24818415/42571627-4809a72a-854a-11e8-90b1-a051fc1a3c04.png)

**Comment by fuerpeng** [comment]
![image](https://user-images.githubusercontent.com/24818415/42571669-577f207c-854a-11e8-9a31-8ccd5c8ddf7b.png)

**Comment by fuerpeng** [comment]
执行的指令是 npm run dev

**Comment by halfrost** [comment]
从报错看，你的 63342 端口没有权限访问。
