### ISSUE TITLE
编译electron的文件存储位置有bug。会导致源程序不断重复编译。

### ISSUE THREAD

**Issue by jayzch** [halfrost/vue-objccn#6]
Packaging app for platform win32 x64 using electron v1.6.11
ENAMETOOLONG: name too long, unlink '/var/folders/rf/f00pr8xn091_zvy7_vyx9p140000gn/T/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/electron-packager/win32-x64/vue-oms-win32-x64/resources/app/node_modules/babel-helper-builder-binary-assignment-operator-visitor/README.md'

**Comment by halfrost** [comment]
好吧。。唯独没有在 Win 上面试过，我把 Linux 和 Mac 跑通了以后，就没有试 Win 平台了。因为 electron 的那个配置也是从官网的 Demo 上抄的一份，我觉得不会有问题，至少 Linux 和 Mac 没有问题，Win 应该没有什么问题，没有想到还有 bug。我找一台 Win 的系统看看哈~

**Comment by jayzch** [comment]
@halfrost 我是在mac上操作的。
mac上编译mac应用  整个目录产生了3g的文件。
mac上编译win也会同样的效果
➜  ~ node -v
v8.2.0
➜  ~ npm -v
5.3.0

**Comment by halfrost** [comment]
哦哦。。。最终你Mac的应用打包也出现了上面的报错？？mac上编译mac应用产生了3G的文件，最终那个app生成出来了么？

**Comment by jayzch** [comment]
会报错。但有东西出来了。但是往里面走。electron-packager里面，可以一直被点进去，死循环的节奏。里面又包里面自己，自己里面又包含了自己。

https://github.com/pfan123/electron-docs
最后我使用的打包命令如下：

electron-packager <sourcedir> <sourcedir> --platform= <platform> win32,darwin --arch=all --version=0.33.7 --out=dist/ --overwrite --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=dist --prune
<sourcedir>： 项目的位置
<sourcedir>： 应用名
--platform=<platform>： 打包的系统(darwin、win32、linux)
--arch=<arch>： 系统位数(ia32、x64)
--icon=<icon>： 指定应用的图标(Mac 为 .icns 文件，Windows 为 .ico 或 .png)
--out <out>： 指定输出的目录
--version=<version>： 指定编译的 electron-prebuilt 版本 简单例子
electron-packager . kaoqin --platform=win32 --arch=all --icon=./public/images/icon.ico --version=0.36.4 --out=../dist/ --overwrite=true --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=dist --prune=true
electron-packager <location of project> <name of project> <platform> <architecture> <electron version> <optional options>
把命令写在`package.json`的scripts里，比如`package`命令，则打包时运行:

**Comment by halfrost** [comment]
哦，好，我一会到家看看哈~谢谢大神的指点！我看看具体哪里有问题。

**Comment by halfrost** [comment]
问题找到了哈，我本地环境是node v6.11.0，npm v5.0.4，我把三个平台都打包了一遍，都没有问题。然后我换到你的最新版，node v8.2.1，npm v5.3.0，确实出现了你说的循环的问题了。大佬提一个PR给我？毕竟这个问题算是你发现并解决的。

**Comment by halfrost** [comment]
OK了，谢谢大神发现问题并修复了哈。（我发现最新版的 npm 打包出来，Resources 文件夹里面支持的语言更多了，包体积增大了一点就在 Resources 文件夹里面了。）再次感谢！
