### ISSUE TITLE
您好，想问一下打包成app是什么原理

### ISSUE THREAD

**Issue by sunsunyongjiu** [halfrost/vue-objccn#8]
可以调用硬件么？是用什么开发，想了解vue打包app的问题，hbuilder或者cordova么？之前结合hbuilder做不知道怎么调用硬件

**Comment by halfrost** [comment]
打包成app桌面端是用的 Electron 框架，原理是它把一个小型的浏览器打包到app应用里面去了。打包成手机端的app用的是cordova，实现原理是通过JSCore，JS通过调用OC代码实现的。调用硬件需要Native支持才行，比如暴露相关封装好的接口，给JS调用。用JS开发。hbuilder我没有用过😅
